language: node_js
node_js: "13"
cache:
  yarn: true
  directories:
    - node_modules
    - client/node_modules
branches:
  only:
    - master
env:
  - DATABASE="mongodb://localhost:27017/mernauth-test"